### PR TITLE
Add Table and Toolbar components

### PR DESCRIPTION
**Pull request by mindreeper2420**
Add the Table and Toolbar components to the Design Manual.

The Table has two variations - default and collapsed, with each having the ability to utilize the `pf-m-expanded` modifier for expandable rows.

## Tables
image
image

## Toolbar
image

### CODE REVIEW

**Comment by mindreeper2420** [comment]
[Front-end table/list component](https://trello.com/c/phXCtuON/859-front-end-table-list-component)

**Comment by mindreeper2420** [comment]
@gdoyle1 I've updated the hover styling on the header sorts in order to match the latest version of PatternFly (our version on developers is older). The outline for the expansion caret has also been fixed. Also, the red underline on the filter dropdowns has been returned to blue.

An additional update will be done for the mobile issues.

**Comment by mindreeper2420** [comment]
@gdoyle1 the mobile view should be fixed now - I've updated the icons rotation as well as the alignment of the register button in the table when the screen is below 768px wide.

**Comment by mindreeper2420** [comment]
@gdoyle1 thoughts on merging this into th design manual site? I'm not sure if it will be needed by the development team, but we can update the release label once it makes it onto the developer site.

**Comment by mindreeper2420** [comment]
@gdoyle1 @sjcox-rh @maryshak1996  Testing on Chrome, I'm only seeing those boxes when clicking on the table header and expand buttons, not when hovering over the elements. Both of these styles are inherited from the version of PatternFly that we are using. I believe it'd be better to get the developer site to update their version (which we inherit) rather than trying to override and then remove in the future. Once that is updated, we'd match what PatternFly currently does for styling.

**Comment by mindreeper2420** [comment]
@sjcox-rh A hover state can be added to the active sorted column. It'll be subtle to mimic the Register button.

Regarding the click states, those come from PatternFly as part of the accessibility improvements. As an 'active' state on click, it has the same visual queues as if a keyboard user has tabbed to the item.

**Comment by mindreeper2420** [comment]
@rogeralloymagnetic as part of this PR to add in the new table component, custom CSS was created that does not exist on the developer site. Here is the code I wrote (pure CSS, not SCSS):

```css
  @media screen and (max-width: 768px) {
    .pf-c-table__toggle .pf-c-button.pf-m-expanded>* {
      transform: rotate(0) !important;
    }
  }
  @media screen and (max-width: 768px) and (min-width: 320px) {
    .rhd-c-table .rhd-m-register {
      justify-self: baseline;
    }
  }
  .rhd-c-table {
    --pf-c-table__expandable-row--before--BackgroundColor: #ee0000;
  }
  .rhd-c-table .pf-c-button:hover:after {
    border-color: transparent;
  }
  .rhd-c-table .rhd-m-register {
    padding-left: 0;
  }
  .rhd-c-table .pf-c-table__sort.pf-m-selected .pf-c-button:hover {
    color: var(--pf-c-button--m-link--hover--Color);
  }
  .rhd-c-table .pf-c-table__sort.pf-m-selected .pf-c-table__sort-indicator:hover {
    color: var(--pf-c-button--m-link--hover--Color);
  }
  .rhd-m-nested-table thead tr {
    border-bottom: 0 !important;
  }
  .rhd-m-nested-table thead tr th {
    padding-bottom: 8px;
  }
  .rhd-m-nested-table tbody tr th {
    padding-top: 8px;
  }
  .rhd-m-nested-table tbody tr td {
    padding-top: 8px;
  }
  .rhd-m-nested-table thead tr>*:first-child {
    padding-left: 0;
  }
  .rhd-m-nested-table tbody tr>*:first-child {
    padding-left: 0;
  }
  .pf-c-table .pf-c-table__expandable-row-content h6 {
    font-size: 14px;
    font-weight: 600;
  }
  .pf-c-table .pf-c-table__expandable-row-content p {
    font-size: 14px;
  }
```

**Comment by rogeralloymagnetic** [comment]
Thanks @mindreeper2420 I'll add that in when I start work on this. 

@sjcox-rh Just a heads up that the events collection work is blocked on this issue. If these new changes are minor enough, I'd like to merge what we have and open a follow-up ticket for tweaks.

**Pull request merged**
